---
title: 根基不稳
date: 2021-12-21 13:41:36
tags:
  - ruby
---

```ruby
class Demo
  def run
    foo      # 正常
    self.foo # 报错: private method `foo' called for #<Demo:0x00007fd39e80c2e8>
  end

  private

  def foo
    puts __method__
  end
end

Demo.new.run
```

今天遇到这个问题的时候, 我这才意识到我的OOP基础有多薄弱...

继续努力

