---
title: 根基不稳
date: 2021-12-21 13:41:36
tags:
  - ruby
---

**2022-05-15 15:50:10 updated**

## Ruby version < 2.7

```ruby
class Demo
  def run
    foo      # 正常
    self.foo # 报错: private method `foo' called for #<Demo:0x00007fd39e80c2e8>
  end

  private

  def foo
    puts __method__
  end
end

Demo.new.run
```

今天遇到这个问题的时候, 我这才意识到我的OOP基础有多薄弱...

继续努力

遇到这个问题的原因是, 使用的ruby版本小于2.7, 这时候不能这么用

+ 之后ruby2.7新增了功能, 允许这种用法了...
    + [changelog: #11297 #16123](https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/)
    + [feature](https://bugs.ruby-lang.org/issues/11297)

